AWSTemplateFormatVersion: '2010-09-09'

Description: Auction System-RDS Definition

Parameters:
  StackName:
    Description: Database Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: auction-system-database

  SubnetId1:
    Description: Subnet ID for DB Instance Subnet Group
    Type: String
  SubnetId2:
    Description: Subnet ID for DB Instance Subnet Group
    Type: String

Resources:
  MyRDSSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: dev-auction-secret
      Description: 'This is the secret for my RDS instance'
      GenerateSecretString:
        SecretStringTemplate: '{"USER": "admin"}'
        GenerateStringKey: 'PASSWORD'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: auction-systems
      DBName: auction_db
      Engine: mysql
      MultiAZ: false
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref MyRDSSecrets, ':SecretString:USER}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref MyRDSSecrets, ':SecretString:PASSWORD}}' ]]
      DBInstanceClass: db.t2.micro
      AllocatedStorage: '20'
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: True
      Port: 3306

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB Subnet Group for Private Subnet
      SubnetIds:
        - !Ref  SubnetId1
        - !Ref SubnetId2

Outputs:
  RDSInstance:
    Description: RDS
    Value: !Ref RDSInstance
    Export:
      Name: !Sub ${StackName}-RDS

  RDSInstanceEndPoint:
    Description: RDS
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub ${StackName}-RDSEndpoint
