name: Manual OpenAPI Spectral Report

on:
  workflow_dispatch:

jobs:
  spectral-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Spectral CLI
        run: npm install -g @stoplight/spectral-cli

      - name: Create report folder
        run: mkdir -p spectral-reports
        
      - name: Run Spectral report for Auction
        run: spectral lint Auction/auctionSwagger.yaml --format html > spectral-reports/auction-report.html

      - name: Run Spectral report for Auth
        run: spectral lint Auth/authSwagger.yaml --format html > spectral-reports/auth-report.html

      - name: Run Spectral report for Teams
        run: spectral lint Teams/open-api.yaml --format html > spectral-reports/teams-report.html

      - name: Run Spectral report for Players
        run: spectral lint Players/open-api.yaml --format html > spectral-reports/players-report.html

      - name: Upload Spectral reports
        uses: actions/upload-artifact@v4
        with:
          name: spectral-reports
          path: spectral-reports/
